name: Cloudflare Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'website/**'
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10

      - name: Build
        run: |
          cd website
          pnpm install
          pnpm run build

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy website/.vitepress/dist --project-name=tuskbot --branch=${{ github.head_ref || github.ref_name }}

      - name: Add PR Comment
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            **Website preview URL:** ${{ steps.deploy.outputs.deployment-url }}
          comment_tag: website_preview