name: Cloudflare Deployment

on:
  push:
    branches:
      - main
      - '**'
    paths:
      - 'website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          cache: true

      - name: Install and Build
        run: |
          cd website
          pnpm install
          pnpm run tusk:build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: tuskbot
          directory: website/.vitepress/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}