name: Cloudflare Deployment

on:
  push:
    branches:
      - main
      - '**'
    paths:
      - 'website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          cache: true

      - name: Build
        run: |
          cd website
          pnpm install
          pnpm run tusk:build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./website/.vitepress/dist --project-name=tuskbot
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
